# Site settings
title: "Coffee break"
author: "Alice Lee"
description: "데이터 및 기술 공부의 흔적을 남기기 위한 블로그, 종종 다른 이야기도 합니다."
keywords: "Blogging, Journalism, Machine-learning"
biography: Data scientist, caffein addict, psychology lover and technician
colophon: 

baseurl: ""
url: "https://coffpsy.wordpress.com"

twitter_username: coffpsy
github_username: Aliceleeme
linkedin_username: jihyelee.0428@gmail.com
facebook_username: 
google-analytics: 

simple_search: 
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
