# Site settings
title: "Coffee breaks with blog"
author: "Alice Lee"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Blogging, Journalism, Machine-learning"
biography: Data scientist and caffein addict from the universe 
colophon: 

baseurl: ""
url: "https://Aliceleeme.github.io"

twitter_username: 
github_username: 
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: 
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
